#' vis_fibre
#'
#' @description A fct function
#' This function visualize a graph that is generated by function `split_tree()`
#' and `index_fibre()`. To visualise FAS sheet, special data transfromation will
#' be needed.
#'
#' By default automatically generated FAS will re-index each node based on leaf index.
#' For example "FDP/1234-1" indicated this fibre node is going to the first splitter
#' The appendix "-1" does not have much meanings. But to avoid misleading readers,
#' `vis_fibre()` will automatically correct name of each fibre node. For cabinet,
#' the new appendix inherit the *fibre_to* fibre index. For other nodes, they inherits
#' *fibre_from* index (as this will make sure each node is unique).
#'
#' @param tg a tree graph generated by auto splice
#' @param treeSpacing,nodeSpacing inherited graph parameter from visIgraph
#' @param select_by default enclosure, recommend fibre_spn
#' This will select highlight only fibre of a certain spine node area.
#'
#'
#' @return visNetwork graph object
#'
#' @export
vis_fibre <- function(tg, treeSpacing = 90, nodeSpacing = 50, select_by = "enclosure") {
  color_list <- conf$colour_of_fibres
  # require fibre_color_id and connecting_cable in database
  tg |>
    activate(nodes) |>
    mutate(to_fibre_index = .E()$fibre_id[match(row_number(), .E()$from)]) |>
    mutate(from_fibre_index = .E()$fibre_id[match(row_number(), .E()$to)]) |>
    mutate(name = ifelse(node_is_root(),
                         paste(enclosure, to_fibre_index, sep = "-"),
                         paste(enclosure, from_fibre_index, sep = "-")
    )) |>
    mutate(fibre_spn = .E()$leaf_spn[match(row_number(), .E()$from)]) |>


    arrange(enclosure, to_fibre_index) |>
    activate(edges) |>

    mutate(title = paste(connecting_cable, fibre_id)) %>% with({
      eqt <- V(.)$name |> str_extract(".+(?=\\-)")
      # V(.)$level <- match(eqt, unique(eqt))
      V(.)$size <- ifelse(V(.)$action == "SPLICE", 6, 4)
      V(.)$color <- c("black")
      V(.)$title <- paste(V(.)$name, V(.)$action)
      V(.)$shape <- ifelse(V(.)$action == "SPLICE", "square", "dot")

      E(.)$color <- map_chr(E(.)$fibre_id, ~color_list[to_color_id(.x)])

      E(.)$width <- c(10)
      E(.)$arrows <- c("")
      E(.)$shadow <- c(T)

      message("Friendly reminded that fibre node has been renamed for the purpose of visualisation")
      visIgraph(., smooth = T, physics = F) |>
        visNodes(shadow = T) |>
        visOptions(selectedBy = select_by) |>
        visHierarchicalLayout(direction = "LR", treeSpacing = treeSpacing, nodeSpacing = nodeSpacing) |>
        visInteraction(hover = T,
                       keyboard = T,
                       dragNodes = F,
                       dragView = T
        )
    })
}



